import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-base-200 flex flex-col">
        <header>
          <Navbar />
        </header>
        <main className="flex-grow min-h-[150vh]">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
